#!/usr/bin/env bash
set -e

usage() {
  cat <<EOF
Usage: gh prop <command> [options]

Manage repository custom properties

Commands:
  list        List properties for a repository
  set         Set a property for a repository
  schema      Get the schema for an organization
  search      Search for a matching property value in a repository

Options:
  -r <owner/repo>   Specify the owner and repository name
  -p <property>     The name of the property
  -v <value>        The value of the property

Examples:
  gh prop list
  gh prop list -r octocat/hello-world
  gh prop set -r octocat/hello-world -p Team -v "Team A"
  gh prop schema
  gh prop schema octocat
  gh prop search -v "Any value"
  gh prop search -p "Team" -v "Team A"
  gh prop search -r octocat/hello-world -p "Team" -v "Team A"
}
EOF
}

set_property() {
  local repo='{owner}/{repo}'
  local prop
  local value
  if [ $# -eq 0 ]; then
    usage
    return 1
  fi

  while getopts "r:p:v:" opt; do
    case $opt in
      r) repo="$OPTARG" ;;
      p) prop="$OPTARG" ;;
      v) value="$OPTARG" ;;
      *) usage ;;
    esac
  done

  if [ -z "$prop" ] || [ -z "$value" ]; then
    echo "error: missing required option" >&2
    usage
    return 1
  fi

  gh api \
    --method PATCH \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    /repos/"$repo"/properties/values \
    -f "properties[][property_name]=$prop" -f "properties[][value]=$value"
}

list() {
  local repo='{owner}/{repo}'

  while getopts "r:" opt; do
    case $opt in
      r) repo="$OPTARG" ;;
      *) usage ;;
    esac
  done

  if [ -z "$repo" ]; then
    usage
    return 1
  fi

  gh api \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    /repos/"$repo"/properties/values
}

schema() {
  local owner='{owner}'
  [ $# -eq 0 ] || owner="$1"

  gh api \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  /orgs/"$owner"/properties/schema
}

search() {
  local repo='{owner}/{repo}'
  local prop
  local value
  if [ $# -eq 0 ]; then
    usage && exit 1
  fi

  while getopts "r:p:v:" opt; do
    case $opt in
      r) repo="$OPTARG";;
      p) prop="$OPTARG";;
      v) value="$OPTARG";;
      *) usage && exit 1;;
    esac
  done

  if [ -z "$value" ]; then
    echo "error: missing required option" >&2
    usage && exit 1
  fi

  repo_props="$(gh prop list -r "${repo}")"

  if [ -z "$prop" ]; then
    result="$(echo "$repo_props" | jq ".[] | .value == \"${value}\"")"
  else
    result="$(echo "$repo_props" | jq ".[] | select(.property_name == \"${prop}\") | .value == \"${value}\"")"
  fi

  if [[ "$result" =~ "true" ]]; then
    echo "✅ Found a match: '${repo}'"
  else
    echo "❌ No match: '${repo}'"
    exit 1
  fi
}

cmd="$1"
[ $# -eq 0 ] || shift 1

case "$cmd" in
-h|--help)
  usage
  ;;
set)
  set_property "$@"
  ;;
list)
  list "$@"
  ;;
schema)
  schema "$@"
  ;;
*)
  usage >&2
  exit 1
  ;;
esac
